### ISSUE TITLE
The link to the solution tutorial brings you to the wrong tutorial

### ISSUE THREAD

**Issue by susancline** [VidyasagarMSC/image-classification-code-engine#1]
I'm trying to follow this blog post and access the tutorial:  https://www.ibm.com/cloud/blog/image-classification-with-ibm-cloud-code-engine-and-tensorflow

If you go down a little on that page you see this:

![image](https://user-images.githubusercontent.com/51341281/109064403-3a01b480-769f-11eb-9c70-cbc1fbd428b4.png)

The link embedded in that paragraph is this:  https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-text-analysis-code-engine

which is not the tutorial I am looking for.  When I searched at the solution-tutorials I could not find the image classification with code engine and tensorflow tutorial.  

1) The link needs to be fixed
2) Does this tutorial still exist?

Thank you!

**Comment by VidyasagarMSC** [comment]
Added a note to the README.md to avoid confusion.
